server:
  port: 9020
  servlet:
    context-path: /users

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user-db
    username: user
    password: password
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secretKey: td2lR4BTX1HsqUm/JsCVf5Os5Q7hJfl9j5Iy7rEB33k=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka