eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: kafka:9092

USER_SERVICE_URI: http://user-service
POST_SERVICE_URI: http://post-service
CONNECTION_SERVICE_URI: http://connection-service
NOTIFICATION_SERVICE_URI: http://notification-service
UPLOADER_SERVICE_URI: http://uploader-service